#!/bin/bash
set -euo pipefail
DOTFILES_DIR="${1:-$(realpath "$(dirname "$0")/..")}"
source "$DOTFILES_DIR/scripts/utils.sh" "$DOTFILES_DIR"

section "Window Manager Stack" "🪟"

log_info "Installing Sway, Waybar, Mako, Wofi..."
sudo dnf install -y sway swaybg swaylock swayidle waybar mako wofi grim slurp wl-clipboard nemo

log_info "Installing KDE Plasma (fallback session)..."
sudo dnf group install -y "kde-desktop-environment"

log_info "Installing SDDM..."
sudo dnf install -y sddm
# --force: some Fedora KDE installs already alias display-manager.service to another
# greeter (e.g. plasmalogin.service) — SDDM must own it so Sway/Plasma are selectable there
sudo systemctl enable --force sddm.service

# Sway has no generated files inside its config dir, so the whole directory can be symlinked
symlink "$DOTFILES_DIR/config/sway" "$HOME/.config/sway"

# Keybind cheat sheet ($mod+slash) — searchable list of sway + other app shortcuts
symlink "$DOTFILES_DIR/scripts/keybinds.sh" "$HOME/.local/bin/sway-keybinds"
chmod +x "$DOTFILES_DIR/scripts/keybinds.sh"

# swaylock config is regenerated by pywal on each 'wallpaper' call — copy static fallback for first boot
mkdir -p "$HOME/.config/swaylock"
if [ ! -f "$HOME/.config/swaylock/config" ]; then
    cp "$DOTFILES_DIR/config/swaylock/config" "$HOME/.config/swaylock/config"
fi

# Waybar: symlink files individually, not the whole dir — the colors-waybar.css
# symlink into ~/.cache/wal below must not land inside the git repo
mkdir -p "$HOME/.config/waybar"
symlink "$DOTFILES_DIR/config/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc"
symlink "$DOTFILES_DIR/config/waybar/style.css"    "$HOME/.config/waybar/style.css"
ln -sf "$HOME/.cache/wal/colors-waybar.css" "$HOME/.config/waybar/colors-waybar.css"

# Wofi has no generated files inside its config dir either: style.css imports colors
# straight from ~/.cache/wal (see its own comment for why), so the whole dir can be symlinked
symlink "$DOTFILES_DIR/config/wofi" "$HOME/.config/wofi"

# Mako is not symlinked — pywal regenerates ~/.config/mako/config on each 'wallpaper' call
# copy static fallback for first boot (before any wallpaper is set)
mkdir -p "$HOME/.config/mako"
if [ ! -f "$HOME/.config/mako/config" ]; then
    cp "$DOTFILES_DIR/config/mako/config" "$HOME/.config/mako/config"
fi

# Only set the default session if no login has happened yet, so a rerun never
# overwrites a session the user picked manually afterwards
AS_USER_FILE="/var/lib/AccountsService/users/${USER}"
if [ ! -f "$AS_USER_FILE" ]; then
    sudo tee "$AS_USER_FILE" > /dev/null <<EOF
[User]
Session=sway.desktop
EOF
fi

log_success "WM setup complete"
