general {
    grace = 0
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/wallpapers/current
    blur_size = 4
    blur_passes = 2
    brightness = 0.7
}

label {
    monitor =
    text = cmd[update:1000] echo "<span font_size='72pt'>$(date +"%H:%M")</span>"
    color = rgba({foreground.strip}e6)
    font_size = 72
    font_family = monospace
    position = 0, 200
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    outer_color = rgba({color2.strip}cc)
    inner_color = rgba({background.strip}99)
    font_color = rgba({foreground.strip}ff)
    check_color = rgba({color6.strip}ff)
    fail_color = rgba({color1.strip}ff)
    placeholder_text = <i>Passwort...</i>
    position = 0, -120
    halign = center
    valign = center
}
